### ISSUE TITLE
abandoned project, similar PyPi name

### ISSUE THREAD

**Issue by ITProKyle** [michilu/sphinxcontrib-externallinks#1]
Hello @michilu,

I am trying to publish a python package to PyPi named [sphinxcontrib.external-links](https://github.com/ITProKyle/sphinxcontrib.external-links). My attempt to publish was met with a `400` because it's name was too similar to a package which I am assuming is yours given the logic that PyPi uses to determine similarity.

It looks like this project has not had any updates in ~10 years and [sphinxcontrib-externallinks](https://pypi.org/project/sphinxcontrib-externallinks/#history) has only had dev (pre-release) versions pushed to PyPi in that time. I was wondering if you would consider pulling the package from PyPi so that someone else (myself) could publish with a similar name.

This request is being made in accordance with [PEP 541](https://peps.python.org/pep-0541/#how-to-request-a-name-transfer).

Thank you for your consideration!

**Comment by michilu** [comment]
Hello @ITProKyle ,

After reviewing the situation and considering the long period of inactivity associated with the existing package, I've decided to remove the package from PyPi as you suggested. This action should resolve the name conflict and allow you to proceed with publishing your package, sphinxcontrib.external-links.

Thank you once again for your contribution to the Python community and for helping maintain the health and vibrancy of the PyPi ecosystem.

Best regards
